FROM python:3.13-slim

# Prevent Python from creating .pyc files
ENV PYTHONDONTWRITEBYTECODE=1

# Send Python output directly to the terminal
ENV PYTHONUNBUFFERED=1
# Set the working directory
WORKDIR /app
# Copy application code
COPY requirements.txt .
# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
# Copy application code
COPY . .

# Create a non-root user
RUN useradd -m appuser
# Change ownership of the application code
RUN chown -R appuser:appuser /app
# Switch to the non-root user
USER appuser
# Start the application
EXPOSE 5000
# Use gunicorn as the WSGI server
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]